# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
    - automattic/a8c-ci-toolkit#mokagio/verbose-tar
    - automattic/nvm#0.3.0

# All current steps use the same agent and environment; we can define them as top-level
agents:
  queue: mac
env:
  IMAGE_ID: xcode-15.2

steps:
  - label: Lint
    key: lint
    command: |
      .buildkite/commands/install-node-dependencies.sh
      echo '--- :eslint: Lint'
      npm run lint
    agents:
      queue: default
    plugins: *common_plugins
    artifact_paths:
      - cache.tar.gz
      - '*.log'

  # Deleted other steps to avoid races in creating the cache, and also getting faster feedback.
